export const allAchievements = [
  {
    id: 'a1',
    title: '實習生',
    description: '完成 1 個關卡',
    rewards: 100,
  },
  {
    id: 'a2',
    title: '新鮮人',
    description: '完成 10 個關卡',
    rewards: 200,
  },
  {
    id: 'a3',
    title: '老鳥',
    description: '完成 50 個關卡',
    rewards: 300,
  },
  {
    id: 'a4',
    title: '高級玩家',
    description: '完成 100 個關卡',
    rewards: 500,
  },
  {
    id: 'a5',
    title: '資深玩家',
    description: '完成 500 個關卡',
    rewards: 500,
  },
  {
    id: 'a6',
    title: '封頂玩家',
    description: '完成 1000 個關卡',
    rewards: 500,
  },
  {
    id: 'b1',
    title: '三星手速',
    description: '在一關中獲得 3 顆星',
    rewards: 100,
  },
  {
    id: 'b2',
    title: '摘星達人 Ⅰ',
    description: '總共獲得 50 顆星',
    rewards: 100,
  },
  {
    id: 'b3',
    title: '摘星達人 Ⅱ',
    description: '總共獲得 100 顆星',
    rewards: 200,
  },
  {
    id: 'b4',
    title: '摘星達人 Ⅲ',
    description: '總共獲得 500 顆星',
    rewards: 300,
  },
  {
    id: 'b5',
    title: '摘星達人 Ⅳ',
    description: '總共獲得 1000 顆星',
    rewards: 400,
  },
  {
    id: 'b6',
    title: '摘星達人 Ⅴ',
    description: '總共獲得 1500 顆星',
    rewards: 500,
  },
  {
    id: 'c1',
    title: 'Combo 新手',
    description: '在一關中達成 3 次連擊',
    rewards: 200,
  },
  {
    id: 'c2',
    title: 'Combo 專家',
    description: '在一關中達成 5 次連擊',
    rewards: 300,
  },
  {
    id: 'c3',
    title: 'Combo 大師',
    description: '在一關中達成 8 次連擊',
    rewards: 500,
  },
  {
    id: 'c4',
    title: 'Combo 超人',
    description: '在一關中達成 12 次連擊',
    rewards: 800,
  },
  {
    id: 'd1',
    title: '小試身手',
    description: '在一關中獲得超過 300 分',
    rewards: 500,
  },
  {
    id: 'd2',
    title: '得心應手',
    description: '在一關中獲得超過 500 分',
    rewards: 800,
  },
  {
    id: 'd3',
    title: '得分高手',
    description: '在一關中獲得超過 800 分',
    rewards: 800,
  },
];
