import { LevelTheme } from '@/models/Level';

export enum LevelType {
  String = 'string',
  ImageUrl = 'imageUrl',
}

export enum MatchCount {
  Two = 2,
  Three = 3,
  Four = 4,
  Five = 5,
}

export const allLevels = [
  {
    id: 1,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: MatchCount.Two,
    questions: [
      require('@/assets/images/questions/animals/cat.png'),
      require('@/assets/images/questions/animals/dog.png'),
      require('@/assets/images/questions/animals/elephant.png'),
      require('@/assets/images/questions/animals/goat.png'),
      require('@/assets/images/questions/animals/horse.png'),
      require('@/assets/images/questions/animals/rabbit.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 400,
    star1Coins: 10,
    star2Coins: 20,
    star3Coins: 50,
  },
  {
    id: 2,
    theme: LevelTheme.Color,
    type: LevelType.String,
    matchCount: 2,
    questions: [
      '#FF5733',
      '#33C1FF',
      '#B833FF',
      '#FFE733',
      '#33FF57',
      '#FF3380',
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 400,
    star1Coins: 10,
    star2Coins: 20,
    star3Coins: 50,
  },
  {
    id: 3,
    theme: LevelTheme.Fruit,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/fruits/apple.png'),
      require('@/assets/images/questions/fruits/avocado.png'),
      require('@/assets/images/questions/fruits/berry.png'),
      require('@/assets/images/questions/fruits/orange.png'),
      require('@/assets/images/questions/fruits/guava.png'),
      require('@/assets/images/questions/fruits/strawberry.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 400,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
  },
  {
    id: 4,
    theme: LevelTheme.Emoji,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/emojis/angry.png'),
      require('@/assets/images/questions/emojis/cool.png'),
      require('@/assets/images/questions/emojis/happy-smile.png'),
      require('@/assets/images/questions/emojis/laugh-smile.png'),
      require('@/assets/images/questions/emojis/sick.png'),
      require('@/assets/images/questions/emojis/sleeping.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 400,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
  },
  {
    id: 5,
    theme: LevelTheme.Emoji,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/emojis/angry.png'),
      require('@/assets/images/questions/emojis/cool.png'),
      require('@/assets/images/questions/emojis/happy-smile.png'),
      require('@/assets/images/questions/emojis/laugh-smile.png'),
      require('@/assets/images/questions/emojis/sick.png'),
      require('@/assets/images/questions/emojis/sleeping.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 400,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
  },
];
