import { LevelTheme } from '@/models/Level';

export enum LevelType {
  String = 'string',
  ImageUrl = 'imageUrl',
}

export enum MatchCount {
  Two = 2,
  Three = 3,
  Four = 4,
  Five = 5,
  Six = 6,
  Seven = 7,
}

export const allLevels = [
  {
    id: 1,
    theme: LevelTheme.Fruit,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/fruits/fruit-1.png'),
      require('@/assets/images/questions/fruits/fruit-10.png'),
      require('@/assets/images/questions/fruits/fruit-11.png'),
    ],
    timer: 25,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 2,
  },
  // {
  //   id: 2,
  //   theme: LevelTheme.Emoji,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/emojis/emoji-11.png'),
  //     require('@/assets/images/questions/emojis/emoji-14.png'),
  //     require('@/assets/images/questions/emojis/emoji-23.png'),
  //   ],
  //   timer: 25,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 2,
  // },
  // {
  //   id: 3,
  //   theme: LevelTheme.CarSign,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/car-signs/car-sign-1.png'),
  //     require('@/assets/images/questions/car-signs/car-sign-2.png'),
  //     require('@/assets/images/questions/car-signs/car-sign-5.png'),
  //     require('@/assets/images/questions/car-signs/car-sign-7.png'),
  //     require('@/assets/images/questions/car-signs/car-sign-9.png'),
  //     require('@/assets/images/questions/car-signs/car-sign-12.png'),
  //   ],
  //   timer: 40,
  //   star1Score: 180,
  //   star2Score: 270,
  //   star3Score: 360,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 4,
  //   theme: LevelTheme.Landmark,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/landmarks/landmark-1.png'),
  //     require('@/assets/images/questions/landmarks/landmark-6.png'),
  //     require('@/assets/images/questions/landmarks/landmark-11.png'),
  //   ],
  //   timer: 25,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 2,
  // },
  // {
  //   id: 5,
  //   theme: LevelTheme.Animal,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/animals/animal-1.svg'),
  //     require('@/assets/images/questions/animals/animal-4.svg'),
  //     require('@/assets/images/questions/animals/animal-5.svg'),
  //     require('@/assets/images/questions/animals/animal-9.svg'),
  //     require('@/assets/images/questions/animals/animal-10.svg'),
  //     require('@/assets/images/questions/animals/animal-15.svg'),
  //   ],
  //   timer: 40,
  //   star1Score: 180,
  //   star2Score: 270,
  //   star3Score: 360,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 6,
  //   theme: LevelTheme.Weather,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/weather/weather-2.png'),
  //     require('@/assets/images/questions/weather/weather-6.png'),
  //     require('@/assets/images/questions/weather/weather-9.png'),
  //   ],
  //   timer: 25,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 2,
  // },
  // {
  //   id: 7,
  //   theme: LevelTheme.BreakFast,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/breakfasts/breakfast-1.svg'),
  //     require('@/assets/images/questions/breakfasts/breakfast-2.svg'),
  //     require('@/assets/images/questions/breakfasts/breakfast-5.svg'),
  //     require('@/assets/images/questions/breakfasts/breakfast-6.svg'),
  //     require('@/assets/images/questions/breakfasts/breakfast-7.svg'),
  //     require('@/assets/images/questions/breakfasts/breakfast-8.svg'),
  //   ],
  //   timer: 40,
  //   star1Score: 180,
  //   star2Score: 270,
  //   star3Score: 360,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 8,
  //   theme: LevelTheme.WaterSport,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/water-sports/water-sport-1.png'),
  //     require('@/assets/images/questions/water-sports/water-sport-2.png'),
  //     require('@/assets/images/questions/water-sports/water-sport-5.png'),
  //     require('@/assets/images/questions/water-sports/water-sport-6.png'),
  //     require('@/assets/images/questions/water-sports/water-sport-8.png'),
  //     require('@/assets/images/questions/water-sports/water-sport-11.png'),
  //   ],
  //   timer: 40,
  //   star1Score: 180,
  //   star2Score: 270,
  //   star3Score: 360,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 9,
  //   theme: LevelTheme.Sushi,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/sushi/sushi-1.png'),
  //     require('@/assets/images/questions/sushi/sushi-3.png'),
  //     require('@/assets/images/questions/sushi/sushi-5.png'),
  //     require('@/assets/images/questions/sushi/sushi-7.png'),
  //     require('@/assets/images/questions/sushi/sushi-9.png'),
  //     require('@/assets/images/questions/sushi/sushi-11.png'),
  //   ],
  //   timer: 40,
  //   star1Score: 180,
  //   star2Score: 270,
  //   star3Score: 360,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 10,
  //   theme: LevelTheme.ChineseWord,
  //   type: LevelType.String,
  //   matchCount: 2,
  //   questions: ['暮', '莫', '募', '墓', '幕', '慕'],
  //   timer: 40,
  //   star1Score: 180,
  //   star2Score: 270,
  //   star3Score: 360,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 11,
  //   theme: LevelTheme.Instrument,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/instruments/instrument-1.png'),
  //     require('@/assets/images/questions/instruments/instrument-2.png'),
  //   ],
  //   timer: 15,
  //   star1Score: 60,
  //   star2Score: 90,
  //   star3Score: 120,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 2,
  // },
  // {
  //   id: 12,
  //   theme: LevelTheme.EcologyGreen,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/ecology-green/ecology-green-1.svg'),
  //     require('@/assets/images/questions/ecology-green/ecology-green-2.svg'),
  //     require('@/assets/images/questions/ecology-green/ecology-green-3.svg'),
  //     require('@/assets/images/questions/ecology-green/ecology-green-4.svg'),
  //     require('@/assets/images/questions/ecology-green/ecology-green-5.svg'),
  //     require('@/assets/images/questions/ecology-green/ecology-green-6.svg'),
  //     require('@/assets/images/questions/ecology-green/ecology-green-7.svg'),
  //     require('@/assets/images/questions/ecology-green/ecology-green-8.svg'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 13,
  //   theme: LevelTheme.Beer,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/beer/beer-1.svg'),
  //     require('@/assets/images/questions/beer/beer-2.svg'),
  //     require('@/assets/images/questions/beer/beer-3.svg'),
  //     require('@/assets/images/questions/beer/beer-4.svg'),
  //     require('@/assets/images/questions/beer/beer-5.svg'),
  //     require('@/assets/images/questions/beer/beer-6.svg'),
  //   ],
  //   timer: 40,
  //   star1Score: 180,
  //   star2Score: 270,
  //   star3Score: 360,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 14,
  //   theme: LevelTheme.Color,
  //   type: LevelType.String,
  //   matchCount: 2,
  //   questions: [
  //     '#FF5733', // 橘紅色
  //     '#33FF57', // 鮮綠色
  //     '#5733FF', // 深紫色
  //     '#FFC300', // 明黃色
  //     '#33C3FF', // 天藍色
  //     '#FF33A8', // 粉紅色
  //   ],
  //   timer: 40,
  //   star1Score: 180,
  //   star2Score: 270,
  //   star3Score: 360,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 15,
  //   theme: LevelTheme.Chess,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/chesses/chess-1.svg'),
  //     require('@/assets/images/questions/chesses/chess-2.svg'),
  //   ],
  //   timer: 15,
  //   star1Score: 60,
  //   star2Score: 90,
  //   star3Score: 120,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 2,
  // },
  // {
  //   id: 16,
  //   theme: LevelTheme.EasterDay,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/easter-day/easter-day-1.svg'),
  //     require('@/assets/images/questions/easter-day/easter-day-2.svg'),
  //   ],
  //   timer: 15,
  //   star1Score: 60,
  //   star2Score: 90,
  //   star3Score: 120,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 2,
  // },
  // {
  //   id: 17,
  //   theme: LevelTheme.Flower,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/flowers/flower-1.svg'),
  //     require('@/assets/images/questions/flowers/flower-2.svg'),
  //     require('@/assets/images/questions/flowers/flower-3.svg'),
  //     require('@/assets/images/questions/flowers/flower-4.svg'),
  //     require('@/assets/images/questions/flowers/flower-5.svg'),
  //     require('@/assets/images/questions/flowers/flower-6.svg'),
  //     require('@/assets/images/questions/flowers/flower-7.svg'),
  //     require('@/assets/images/questions/flowers/flower-8.svg'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 18,
  //   theme: LevelTheme.ZodiacChinese,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/zodiac-chinese/zodiac-1.png'),
  //     require('@/assets/images/questions/zodiac-chinese/zodiac-2.png'),
  //     require('@/assets/images/questions/zodiac-chinese/zodiac-3.png'),
  //     require('@/assets/images/questions/zodiac-chinese/zodiac-4.png'),
  //     require('@/assets/images/questions/zodiac-chinese/zodiac-5.png'),
  //     require('@/assets/images/questions/zodiac-chinese/zodiac-6.png'),
  //     require('@/assets/images/questions/zodiac-chinese/zodiac-7.png'),
  //     require('@/assets/images/questions/zodiac-chinese/zodiac-8.png'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 19,
  //   theme: LevelTheme.User,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/users/user-1.svg'),
  //     require('@/assets/images/questions/users/user-2.svg'),
  //   ],
  //   timer: 15,
  //   star1Score: 60,
  //   star2Score: 90,
  //   star3Score: 120,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 2,
  // },
  // {
  //   id: 20,
  //   theme: LevelTheme.Color,
  //   type: LevelType.String,
  //   matchCount: 2,
  //   questions: [
  //     '#E1F5FE',
  //     '#303F9F',
  //     '#039BE5',
  //     '#01579B',
  //     '#B2EBF2',
  //     '#00BCD4',
  //     '#00838F',
  //     '#82B1FF',
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // // -- 20 --
  // {
  //   id: 21,
  //   theme: LevelTheme.Coin,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/coins/coin-1.png'),
  //     require('@/assets/images/questions/coins/coin-2.png'),
  //     require('@/assets/images/questions/coins/coin-3.png'),
  //     require('@/assets/images/questions/coins/coin-4.png'),
  //     require('@/assets/images/questions/coins/coin-5.png'),
  //     require('@/assets/images/questions/coins/coin-6.png'),
  //     require('@/assets/images/questions/coins/coin-7.png'),
  //     require('@/assets/images/questions/coins/coin-8.png'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 22,
  //   theme: LevelTheme.Leaves,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/leaves/leaves-1.png'),
  //     require('@/assets/images/questions/leaves/leaves-2.png'),
  //     require('@/assets/images/questions/leaves/leaves-3.png'),
  //     require('@/assets/images/questions/leaves/leaves-4.png'),
  //     require('@/assets/images/questions/leaves/leaves-5.png'),
  //     require('@/assets/images/questions/leaves/leaves-6.png'),
  //     require('@/assets/images/questions/leaves/leaves-7.png'),
  //     require('@/assets/images/questions/leaves/leaves-8.png'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 23,
  //   theme: LevelTheme.Emoji,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/emojis/emoji-21.png'),
  //     require('@/assets/images/questions/emojis/emoji-22.png'),
  //     require('@/assets/images/questions/emojis/emoji-23.png'),
  //     require('@/assets/images/questions/emojis/emoji-24.png'),
  //     require('@/assets/images/questions/emojis/emoji-25.png'),
  //     require('@/assets/images/questions/emojis/emoji-26.png'),
  //     require('@/assets/images/questions/emojis/emoji-27.png'),
  //     require('@/assets/images/questions/emojis/emoji-28.png'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 24,
  //   theme: LevelTheme.Transport,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/transports/transport-1.png'),
  //     require('@/assets/images/questions/transports/transport-2.png'),
  //     require('@/assets/images/questions/transports/transport-3.png'),
  //     require('@/assets/images/questions/transports/transport-4.png'),
  //     require('@/assets/images/questions/transports/transport-5.png'),
  //     require('@/assets/images/questions/transports/transport-6.png'),
  //     require('@/assets/images/questions/transports/transport-7.png'),
  //     require('@/assets/images/questions/transports/transport-8.png'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 25,
  //   theme: LevelTheme.Ball,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/balls/ball-1.svg'),
  //     require('@/assets/images/questions/balls/ball-2.svg'),
  //     require('@/assets/images/questions/balls/ball-3.svg'),
  //     require('@/assets/images/questions/balls/ball-4.svg'),
  //     require('@/assets/images/questions/balls/ball-5.svg'),
  //     require('@/assets/images/questions/balls/ball-6.svg'),
  //     require('@/assets/images/questions/balls/ball-7.svg'),
  //     require('@/assets/images/questions/balls/ball-8.svg'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 26,
  //   theme: LevelTheme.Christmas,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/christmas/christmas-1.svg'),
  //     require('@/assets/images/questions/christmas/christmas-2.svg'),
  //     require('@/assets/images/questions/christmas/christmas-3.svg'),
  //     require('@/assets/images/questions/christmas/christmas-4.svg'),
  //     require('@/assets/images/questions/christmas/christmas-5.svg'),
  //     require('@/assets/images/questions/christmas/christmas-6.svg'),
  //     require('@/assets/images/questions/christmas/christmas-7.svg'),
  //     require('@/assets/images/questions/christmas/christmas-8.svg'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 27,
  //   theme: LevelTheme.ZodiacWestern,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/zodiac-western/zodiac-western-1.svg'),
  //     require('@/assets/images/questions/zodiac-western/zodiac-western-2.svg'),
  //     require('@/assets/images/questions/zodiac-western/zodiac-western-3.svg'),
  //     require('@/assets/images/questions/zodiac-western/zodiac-western-4.svg'),
  //     require('@/assets/images/questions/zodiac-western/zodiac-western-5.svg'),
  //     require('@/assets/images/questions/zodiac-western/zodiac-western-6.svg'),
  //     require('@/assets/images/questions/zodiac-western/zodiac-western-7.svg'),
  //     require('@/assets/images/questions/zodiac-western/zodiac-western-8.svg'),
  //   ],
  //   timer: 60,
  //   star1Score: 240,
  //   star2Score: 360,
  //   star3Score: 480,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 28,
  //   theme: LevelTheme.Monster,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/monsters/monster-1.svg'),
  //     require('@/assets/images/questions/monsters/monster-2.svg'),
  //     require('@/assets/images/questions/monsters/monster-3.svg'),
  //   ],
  //   timer: 40,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 29,
  //   theme: LevelTheme.Lock,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/locks/lock-1.svg'),
  //     require('@/assets/images/questions/locks/lock-2.svg'),
  //     require('@/assets/images/questions/locks/lock-3.svg'),
  //   ],
  //   timer: 40,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 30,
  //   theme: LevelTheme.Ancient,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/ancients/ancient-1.jpg'),
  //     require('@/assets/images/questions/ancients/ancient-2.jpg'),
  //     require('@/assets/images/questions/ancients/ancient-3.jpg'),
  //   ],
  //   timer: 40,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 31,
  //   theme: LevelTheme.Battery,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/battery/battery-1.svg'),
  //     require('@/assets/images/questions/battery/battery-2.svg'),
  //     require('@/assets/images/questions/battery/battery-3.svg'),
  //   ],
  //   timer: 40,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 32,
  //   theme: LevelTheme.Weather,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/weather/weather-1.png'),
  //     require('@/assets/images/questions/weather/weather-2.png'),
  //     require('@/assets/images/questions/weather/weather-3.png'),
  //   ],
  //   timer: 40,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 33,
  //   theme: LevelTheme.Battery,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/gifts/gift-1.png'),
  //     require('@/assets/images/questions/gifts/gift-2.png'),
  //     require('@/assets/images/questions/gifts/gift-3.png'),
  //   ],
  //   timer: 40,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 34,
  //   theme: LevelTheme.ChineseEra,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/chinese-era/chinese-era-1.png'),
  //     require('@/assets/images/questions/chinese-era/chinese-era-2.png'),
  //     require('@/assets/images/questions/chinese-era/chinese-era-3.png'),
  //   ],
  //   timer: 40,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 35,
  //   theme: LevelTheme.CowboyHat,
  //   type: LevelType.ImageUrl,
  //   matchCount: 3,
  //   questions: [
  //     require('@/assets/images/questions/cowboy-hats/hat-1.png'),
  //     require('@/assets/images/questions/cowboy-hats/hat-2.png'),
  //     require('@/assets/images/questions/cowboy-hats/hat-3.png'),
  //   ],
  //   timer: 40,
  //   star1Score: 90,
  //   star2Score: 135,
  //   star3Score: 180,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 3,
  // },
  // {
  //   id: 36,
  //   theme: LevelTheme.Jersey,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/jersey/jersey-1.png'),
  //     require('@/assets/images/questions/jersey/jersey-2.png'),
  //     require('@/assets/images/questions/jersey/jersey-3.png'),
  //     require('@/assets/images/questions/jersey/jersey-4.png'),
  //     require('@/assets/images/questions/jersey/jersey-5.png'),
  //     require('@/assets/images/questions/jersey/jersey-6.png'),
  //     require('@/assets/images/questions/jersey/jersey-7.png'),
  //     require('@/assets/images/questions/jersey/jersey-8.png'),
  //     require('@/assets/images/questions/jersey/jersey-9.png'),
  //     require('@/assets/images/questions/jersey/jersey-10.png'),
  //   ],
  //   timer: 60,
  //   star1Score: 300,
  //   star2Score: 450,
  //   star3Score: 600,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 37,
  //   theme: LevelTheme.Animal,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/animals/animal-2.svg'),
  //     require('@/assets/images/questions/animals/animal-4.svg'),
  //     require('@/assets/images/questions/animals/animal-6.svg'),
  //     require('@/assets/images/questions/animals/animal-8.svg'),
  //     require('@/assets/images/questions/animals/animal-10.svg'),
  //     require('@/assets/images/questions/animals/animal-12.svg'),
  //     require('@/assets/images/questions/animals/animal-14.svg'),
  //     require('@/assets/images/questions/animals/animal-16.svg'),
  //     require('@/assets/images/questions/animals/animal-18.svg'),
  //     require('@/assets/images/questions/animals/animal-20.svg'),
  //   ],
  //   timer: 60,
  //   star1Score: 300,
  //   star2Score: 450,
  //   star3Score: 600,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 38,
  //   theme: LevelTheme.Instrument,
  //   type: LevelType.ImageUrl,
  //   matchCount: 2,
  //   questions: [
  //     require('@/assets/images/questions/instruments/instrument-2.png'),
  //     require('@/assets/images/questions/instruments/instrument-3.png'),
  //     require('@/assets/images/questions/instruments/instrument-4.png'),
  //     require('@/assets/images/questions/instruments/instrument-5.png'),
  //     require('@/assets/images/questions/instruments/instrument-8.png'),
  //     require('@/assets/images/questions/instruments/instrument-9.png'),
  //     require('@/assets/images/questions/instruments/instrument-10.png'),
  //     require('@/assets/images/questions/instruments/instrument-11.png'),
  //     require('@/assets/images/questions/instruments/instrument-12.png'),
  //     require('@/assets/images/questions/instruments/instrument-13.png'),
  //   ],
  //   timer: 60,
  //   star1Score: 300,
  //   star2Score: 450,
  //   star3Score: 600,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
  // {
  //   id: 39,
  //   theme: LevelTheme.ChineseWord,
  //   type: LevelType.String,
  //   matchCount: 2,
  //   questions: ['魑', '魅', '魍', '魎', '魊', '魈', '魃', '魁', '魋', '鬾'],
  //   timer: 60,
  //   star1Score: 300,
  //   star2Score: 450,
  //   star3Score: 600,
  //   star1Coins: 10,
  //   star2Coins: 30,
  //   star3Coins: 50,
  //   columns: 4,
  // },
];
