import { LevelTheme } from '@/models/Level';

export enum LevelType {
  String = 'string',
  ImageUrl = 'imageUrl',
}

export enum MatchCount {
  Two = 2,
  Three = 3,
  Four = 4,
  Five = 5,
}

export const allLevels = [
  {
    id: 1,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: MatchCount.Two,
    questions: [
      require('@/assets/images/questions/animals/animal-1.png'),
      require('@/assets/images/questions/animals/animal-2.png'),
      require('@/assets/images/questions/animals/animal-3.png'),
      require('@/assets/images/questions/animals/animal-4.png'),
      require('@/assets/images/questions/animals/animal-5.png'),
      require('@/assets/images/questions/animals/animal-6.png'),
      require('@/assets/images/questions/animals/animal-7.png'),
      require('@/assets/images/questions/animals/animal-8.png'),
      require('@/assets/images/questions/animals/animal-9.png'),
      require('@/assets/images/questions/animals/animal-10.png'),
      require('@/assets/images/questions/animals/animal-11.png'),
      require('@/assets/images/questions/animals/animal-12.png'),
      require('@/assets/images/questions/animals/animal-13.png'),
      require('@/assets/images/questions/animals/animal-14.png'),
      require('@/assets/images/questions/animals/animal-15.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 20,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 2,
    theme: LevelTheme.Color,
    type: LevelType.String,
    matchCount: 2,
    questions: [
      '#FF5733',
      '#33C1FF',
      '#B833FF',
      '#FFE733',
      '#33FF57',
      '#FF3380',
      '#dddd',
      '#123',
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 20,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 3,
    theme: LevelTheme.Fruit,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/fruits/fruit-1.png'),
      require('@/assets/images/questions/fruits/fruit-2.png'),
      require('@/assets/images/questions/fruits/fruit-3.png'),
      require('@/assets/images/questions/fruits/fruit-4.png'),
      require('@/assets/images/questions/fruits/fruit-5.png'),
      require('@/assets/images/questions/fruits/fruit-6.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 4,
    theme: LevelTheme.Emoji,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/emojis/emoji-1.png'),
      require('@/assets/images/questions/emojis/emoji-2.png'),
      require('@/assets/images/questions/emojis/emoji-3.png'),
      require('@/assets/images/questions/emojis/emoji-4.png'),
      require('@/assets/images/questions/emojis/emoji-5.png'),
      require('@/assets/images/questions/emojis/emoji-6.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 5,
    theme: LevelTheme.Landmark,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/landmarks/landmark-1.png'),
      require('@/assets/images/questions/landmarks/landmark-2.png'),
      require('@/assets/images/questions/landmarks/landmark-3.png'),
      require('@/assets/images/questions/landmarks/landmark-4.png'),
      require('@/assets/images/questions/landmarks/landmark-5.png'),
      require('@/assets/images/questions/landmarks/landmark-6.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 6,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gifts/gift-1.png'),
      require('@/assets/images/questions/gifts/gift-3.png'),
      require('@/assets/images/questions/gifts/gift-5.png'),
      require('@/assets/images/questions/gifts/gift-7.png'),
      require('@/assets/images/questions/gifts/gift-9.png'),
      require('@/assets/images/questions/gifts/gift-10.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 7,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leaves/leaves-1.png'),
      require('@/assets/images/questions/leaves/leaves-4.png'),
      require('@/assets/images/questions/leaves/leaves-5.png'),
      require('@/assets/images/questions/leaves/leaves-8.png'),
      require('@/assets/images/questions/leaves/leaves-10.png'),
      require('@/assets/images/questions/leaves/leaves-12.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 8,
    theme: LevelTheme.Instrument,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/instruments/instrument-1.png'),
      require('@/assets/images/questions/instruments/instrument-2.png'),
      require('@/assets/images/questions/instruments/instrument-3.png'),
      require('@/assets/images/questions/instruments/instrument-4.png'),
      require('@/assets/images/questions/instruments/instrument-5.png'),
      require('@/assets/images/questions/instruments/instrument-6.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 9,
    theme: LevelTheme.Transport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/transports/transport-1.png'),
      require('@/assets/images/questions/transports/transport-2.png'),
      require('@/assets/images/questions/transports/transport-3.png'),
      require('@/assets/images/questions/transports/transport-4.png'),
      require('@/assets/images/questions/transports/transport-5.png'),
      require('@/assets/images/questions/transports/transport-6.png'),
    ],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 10,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['幕', '墓', '募', '暮', '寞', '冪'],
    timer: 60,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 11,
    theme: LevelTheme.Entertainments,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/entertainments/entertainment-1.png'),
      require('@/assets/images/questions/entertainments/entertainment-2.png'),
      require('@/assets/images/questions/entertainments/entertainment-3.png'),
      require('@/assets/images/questions/entertainments/entertainment-4.png'),
      require('@/assets/images/questions/entertainments/entertainment-5.png'),
      require('@/assets/images/questions/entertainments/entertainment-6.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 12,
    theme: LevelTheme.ChineseEra,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/chinese-era/chinese-era-1.png'),
      require('@/assets/images/questions/chinese-era/chinese-era-2.png'),
      require('@/assets/images/questions/chinese-era/chinese-era-3.png'),
      require('@/assets/images/questions/chinese-era/chinese-era-4.png'),
      require('@/assets/images/questions/chinese-era/chinese-era-5.png'),
      require('@/assets/images/questions/chinese-era/chinese-era-6.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 13,
    theme: LevelTheme.Envelopes,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/envelopes/envelope-1.png'),
      require('@/assets/images/questions/envelopes/envelope-2.png'),
      require('@/assets/images/questions/envelopes/envelope-3.png'),
      require('@/assets/images/questions/envelopes/envelope-4.png'),
      require('@/assets/images/questions/envelopes/envelope-5.png'),
      require('@/assets/images/questions/envelopes/envelope-6.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 14,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/trees/tree-1.png'),
      require('@/assets/images/questions/trees/tree-2.png'),
      require('@/assets/images/questions/trees/tree-3.png'),
      require('@/assets/images/questions/trees/tree-4.png'),
      require('@/assets/images/questions/trees/tree-5.png'),
      require('@/assets/images/questions/trees/tree-6.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 15,
    theme: LevelTheme.Christmas,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/christmas/christmas-1.png'),
      require('@/assets/images/questions/christmas/christmas-2.png'),
      require('@/assets/images/questions/christmas/christmas-3.png'),
      require('@/assets/images/questions/christmas/christmas-4.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 16,
    theme: LevelTheme.Planet,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/planets/planet-1.png'),
      require('@/assets/images/questions/planets/planet-2.png'),
      require('@/assets/images/questions/planets/planet-3.png'),
      require('@/assets/images/questions/planets/planet-4.png'),
      require('@/assets/images/questions/planets/planet-5.png'),
      require('@/assets/images/questions/planets/planet-6.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 17,
    theme: LevelTheme.Ball,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/balls/ball-1.png'),
      require('@/assets/images/questions/balls/ball-2.png'),
      require('@/assets/images/questions/balls/ball-3.png'),
      require('@/assets/images/questions/balls/ball-4.png'),
      require('@/assets/images/questions/balls/ball-5.png'),
      require('@/assets/images/questions/balls/ball-6.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 18,
    theme: LevelTheme.Zodiac,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/zodiac/zodiac-1.png'),
      require('@/assets/images/questions/zodiac/zodiac-2.png'),
      require('@/assets/images/questions/zodiac/zodiac-3.png'),
      require('@/assets/images/questions/zodiac/zodiac-4.png'),
    ],
    timer: 60,
    star1Score: 140,
    star2Score: 210,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 19,
    theme: LevelTheme.Halloween,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/halloween/halloween-1.png'),
      require('@/assets/images/questions/halloween/halloween-2.png'),
      require('@/assets/images/questions/halloween/halloween-3.png'),
      require('@/assets/images/questions/halloween/halloween-4.png'),
      require('@/assets/images/questions/halloween/halloween-5.png'),
      require('@/assets/images/questions/halloween/halloween-6.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 20,
    theme: LevelTheme.Battery,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/battery/battery-1.png'),
      require('@/assets/images/questions/battery/battery-2.png'),
      require('@/assets/images/questions/battery/battery-3.png'),
      require('@/assets/images/questions/battery/battery-4.png'),
      require('@/assets/images/questions/battery/battery-5.png'),
      require('@/assets/images/questions/battery/battery-6.png'),
    ],
    timer: 50,
    star1Score: 200,
    star2Score: 350,
    star3Score: 430,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 21,
    theme: LevelTheme.Color,
    type: LevelType.String,
    matchCount: 2,
    questions: [
      '#FF5733',
      '#33FF57',
      '#3357FF',
      '#FF33A8',
      '#33FFF5',
      '#F5FF33',
      '#A833FF',
      '#FF8C33',
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 22,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.png'),
      require('@/assets/images/questions/cactus/cactus-3.png'),
      require('@/assets/images/questions/cactus/cactus-8.png'),
      require('@/assets/images/questions/cactus/cactus-10.png'),
      require('@/assets/images/questions/cactus/cactus-11.png'),
      require('@/assets/images/questions/cactus/cactus-12.png'),
      require('@/assets/images/questions/cactus/cactus-15.png'),
      require('@/assets/images/questions/cactus/cactus-16.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 23,
    theme: LevelTheme.File,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/files/file-1.png'),
      require('@/assets/images/questions/files/file-2.png'),
      require('@/assets/images/questions/files/file-3.png'),
      require('@/assets/images/questions/files/file-4.png'),
      require('@/assets/images/questions/files/file-5.png'),
      require('@/assets/images/questions/files/file-6.png'),
      require('@/assets/images/questions/files/file-7.png'),
      require('@/assets/images/questions/files/file-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 24,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-1.png'),
      require('@/assets/images/questions/weather/weather-2.png'),
      require('@/assets/images/questions/weather/weather-3.png'),
      require('@/assets/images/questions/weather/weather-4.png'),
      require('@/assets/images/questions/weather/weather-5.png'),
      require('@/assets/images/questions/weather/weather-6.png'),
      require('@/assets/images/questions/weather/weather-7.png'),
      require('@/assets/images/questions/weather/weather-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 25,
    theme: LevelTheme.Avatar,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/avatars/avatar-1.png'),
      require('@/assets/images/questions/avatars/avatar-2.png'),
      require('@/assets/images/questions/avatars/avatar-5.png'),
      require('@/assets/images/questions/avatars/avatar-8.png'),
      require('@/assets/images/questions/avatars/avatar-10.png'),
      require('@/assets/images/questions/avatars/avatar-12.png'),
      require('@/assets/images/questions/avatars/avatar-15.png'),
      require('@/assets/images/questions/avatars/avatar-22.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 26,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['魁', '魂', '魃', '魅', '魍', '魎', '魏', '魄'],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 27,
    theme: LevelTheme.Coin,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/coins/coin-1.png'),
      require('@/assets/images/questions/coins/coin-2.png'),
      require('@/assets/images/questions/coins/coin-3.png'),
      require('@/assets/images/questions/coins/coin-4.png'),
      require('@/assets/images/questions/coins/coin-5.png'),
      require('@/assets/images/questions/coins/coin-6.png'),
      require('@/assets/images/questions/coins/coin-7.png'),
      require('@/assets/images/questions/coins/coin-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 28,
    theme: LevelTheme.CarSign,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/car-signs/car-sign-1.png'),
      require('@/assets/images/questions/car-signs/car-sign-2.png'),
      require('@/assets/images/questions/car-signs/car-sign-3.png'),
      require('@/assets/images/questions/car-signs/car-sign-4.png'),
      require('@/assets/images/questions/car-signs/car-sign-5.png'),
      require('@/assets/images/questions/car-signs/car-sign-6.png'),
      require('@/assets/images/questions/car-signs/car-sign-7.png'),
      require('@/assets/images/questions/car-signs/car-sign-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 29,
    theme: LevelTheme.CowboyHat,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cowboy-hats/hat-1.png'),
      require('@/assets/images/questions/cowboy-hats/hat-2.png'),
      require('@/assets/images/questions/cowboy-hats/hat-3.png'),
      require('@/assets/images/questions/cowboy-hats/hat-4.png'),
      require('@/assets/images/questions/cowboy-hats/hat-5.png'),
      require('@/assets/images/questions/cowboy-hats/hat-6.png'),
      require('@/assets/images/questions/cowboy-hats/hat-7.png'),
      require('@/assets/images/questions/cowboy-hats/hat-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 30,
    theme: LevelTheme.MapPin,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/map-pins/gps-1.png'),
      require('@/assets/images/questions/map-pins/gps-2.png'),
      require('@/assets/images/questions/map-pins/gps-3.png'),
      require('@/assets/images/questions/map-pins/gps-4.png'),
      require('@/assets/images/questions/map-pins/gps-5.png'),
      require('@/assets/images/questions/map-pins/gps-6.png'),
      require('@/assets/images/questions/map-pins/gps-7.png'),
      require('@/assets/images/questions/map-pins/gps-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 31,
    theme: LevelTheme.WashHand,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/wash-hands/hand-1.png'),
      require('@/assets/images/questions/wash-hands/hand-2.png'),
      require('@/assets/images/questions/wash-hands/hand-3.png'),
      require('@/assets/images/questions/wash-hands/hand-4.png'),
      require('@/assets/images/questions/wash-hands/hand-5.png'),
      require('@/assets/images/questions/wash-hands/hand-6.png'),
      require('@/assets/images/questions/wash-hands/hand-7.png'),
      require('@/assets/images/questions/wash-hands/hand-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 32,
    theme: LevelTheme.Clothes,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/clothes/clothe-1.png'),
      require('@/assets/images/questions/clothes/clothe-2.png'),
      require('@/assets/images/questions/clothes/clothe-3.png'),
      require('@/assets/images/questions/clothes/clothe-4.png'),
      require('@/assets/images/questions/clothes/clothe-5.png'),
      require('@/assets/images/questions/clothes/clothe-6.png'),
      require('@/assets/images/questions/clothes/clothe-7.png'),
      require('@/assets/images/questions/clothes/clothe-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 33,
    theme: LevelTheme.Hat,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/hats/hat-1.png'),
      require('@/assets/images/questions/hats/hat-2.png'),
      require('@/assets/images/questions/hats/hat-3.png'),
      require('@/assets/images/questions/hats/hat-4.png'),
      require('@/assets/images/questions/hats/hat-5.png'),
      require('@/assets/images/questions/hats/hat-6.png'),
      require('@/assets/images/questions/hats/hat-7.png'),
      require('@/assets/images/questions/hats/hat-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 34,
    theme: LevelTheme.Beer,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/beers/beer-1.png'),
      require('@/assets/images/questions/beers/beer-2.png'),
      require('@/assets/images/questions/beers/beer-3.png'),
      require('@/assets/images/questions/beers/beer-4.png'),
      require('@/assets/images/questions/beers/beer-5.png'),
      require('@/assets/images/questions/beers/beer-6.png'),
      require('@/assets/images/questions/beers/beer-7.png'),
      require('@/assets/images/questions/beers/beer-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 35,
    theme: LevelTheme.Sushi,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/sushi/sushi-1.png'),
      require('@/assets/images/questions/sushi/sushi-2.png'),
      require('@/assets/images/questions/sushi/sushi-3.png'),
      require('@/assets/images/questions/sushi/sushi-4.png'),
      require('@/assets/images/questions/sushi/sushi-5.png'),
      require('@/assets/images/questions/sushi/sushi-6.png'),
      require('@/assets/images/questions/sushi/sushi-7.png'),
      require('@/assets/images/questions/sushi/sushi-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 36,
    theme: LevelTheme.Party,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/party/party-1.png'),
      require('@/assets/images/questions/party/party-2.png'),
      require('@/assets/images/questions/party/party-3.png'),
      require('@/assets/images/questions/party/party-4.png'),
      require('@/assets/images/questions/party/party-5.png'),
      require('@/assets/images/questions/party/party-6.png'),
      require('@/assets/images/questions/party/party-7.png'),
      require('@/assets/images/questions/party/party-8.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 37,
    theme: LevelTheme.Dice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/dices/dice-1.png'),
      require('@/assets/images/questions/dices/dice-2.png'),
      require('@/assets/images/questions/dices/dice-3.png'),
      require('@/assets/images/questions/dices/dice-4.png'),
    ],
    timer: 50,
    star1Score: 250,
    star2Score: 380,
    star3Score: 500,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
];
