import { LevelTheme } from '@/models/Level';

export const allThemes = [
  {
    id: 1,
    title: '動物',
    type: LevelTheme.Animal,
    image: require('@/assets/images/questions/animal/animal-28.svg'),
  },
  {
    id: 2,
    title: '顏色',
    type: LevelTheme.Color,
    image: require('@/assets/images/themes/color.svg'),
  },
  {
    id: 3,
    title: '人物',
    type: LevelTheme.Avatar,
    image: require('@/assets/images/questions/avatar/avatar-1.svg'),
  },
  {
    id: 4,
    title: '表情',
    type: LevelTheme.Emoji,
    image: require('@/assets/images/questions/emoji/emoji-34.svg'),
    unlockStars: 90,
  },
  {
    id: 5,
    title: '中文字',
    type: LevelTheme.ChineseWord,
    image: require('@/assets/images/themes/chinese.svg'),
    unlockStars: 120,
  },
  {
    id: 6,
    title: '樹木',
    type: LevelTheme.Tree,
    image: require('@/assets/images/questions/tree/tree-18.svg'),
    unlockStars: 150,
  },
  {
    id: 7,
    title: '錢幣',
    type: LevelTheme.Coin,
    image: require('@/assets/images/questions/coin/coin-10.svg'),
    unlockStars: 180,
  },
  {
    id: 8,
    title: '禮物盒',
    type: LevelTheme.Gift,
    image: require('@/assets/images/questions/gift/gift-7.svg'),
    unlockStars: 210,
  },
  {
    id: 9,
    title: '葉子',
    type: LevelTheme.Leaves,
    image: require('@/assets/images/questions/leave/leave-13.svg'),
    unlockStars: 240,
  },
  {
    id: 10,
    title: '公共標誌',
    type: LevelTheme.Notice,
    image: require('@/assets/images/questions/notice/notice-38.svg'),
    unlockStars: 270,
  },
  {
    id: 11,
    title: '傢俱',
    type: LevelTheme.Furniture,
    image: require('@/assets/images/questions/furniture/furniture-3.svg'),
    unlockStars: 300,
  },
  {
    id: 12,
    title: '郵件',
    type: LevelTheme.Email,
    image: require('@/assets/images/questions/email/email-11.svg'),
    unlockStars: 330,
  },
  {
    id: 13,
    title: '太空',
    type: LevelTheme.Space,
    image: require('@/assets/images/questions/space/space-3.svg'),
    unlockStars: 360,
  },
  {
    id: 14,
    title: '城市建築',
    type: LevelTheme.CityBuilding,
    image: require('@/assets/images/questions/city-building/city-building-11.svg'),
    unlockStars: 390,
  },
  {
    id: 15,
    title: '水上活動',
    type: LevelTheme.WaterSport,
    image: require('@/assets/images/questions/water-sport/water-sport-1.svg'),
    unlockStars: 420,
  },
  {
    id: 16,
    title: '古人',
    type: LevelTheme.Ancient,
    image: require('@/assets/images/questions/ancient/ancient-1.jpg'),
    price: 280,
  },
  {
    id: 17,
    title: '仙人掌',
    type: LevelTheme.Cactus,
    image: require('@/assets/images/questions/cactus/cactus-3.svg'),
    price: 360,
  },
  {
    id: 18,
    title: '甜點飲料',
    type: LevelTheme.SweetDrink,
    image: require('@/assets/images/questions/sweet-drink/sweet-drink-5.svg'),
    price: 360,
  },
  {
    id: 19,
    title: '草叢',
    type: LevelTheme.Grass,
    image: require('@/assets/images/questions/grass/grass-2.png'),
    price: 400,
  },
  {
    id: 20,
    title: '世界景點',
    type: LevelTheme.Landmark,
    image: require('@/assets/images/questions/landmark/landmark-6.svg'),
    price: 480,
  },
  {
    id: 21,
    title: '天氣',
    type: LevelTheme.Weather,
    image: require('@/assets/images/questions/weather/weather-2.svg'),
    price: 480,
  },
  {
    id: 22,
    title: '智慧手錶',
    type: LevelTheme.SmartWatch,
    image: require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
    price: 1000,
  },
  {
    id: 23,
    title: '摺紙',
    type: LevelTheme.Origami,
    image: require('@/assets/images/questions/origami/origami-2.svg'),
    price: 1000,
  },
  {
    id: 24,
    title: '滑動手勢',
    type: LevelTheme.Gestures,
    image: require('@/assets/images/questions/gestures/gestures-2.svg'),
    price: 1320,
  },
];
