import { LevelTheme, LevelType } from '@/models/Level';

export const ancientThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
  },
];