import { Level, LevelTheme, LevelType } from '@/models/Level';

export const ancientThemeLevels: Level[] = [
  {
    id: 1,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 2,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 3,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
    timer: 60,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 4,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
    ],
    timer: 70,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 5,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
    timer: 80,
    star1Score: 360,
    star2Score: 480,
    star3Score: 720,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 6,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
    ],
    timer: 30,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 7,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
    timer: 30,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 8,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
    timer: 30,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 9,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
    timer: 70,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 10,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
    ],
    timer: 80,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 11,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
    ],
    timer: 30,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 12,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
    ],
    timer: 30,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 13,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
    ],
    timer: 30,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 14,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
    timer: 30,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 15,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
    ],
    timer: 40,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 16,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
    timer: 40,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 17,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
    timer: 40,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 18,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
    ],
    timer: 50,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 19,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
    ],
    timer: 50,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 20,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
    ],
    timer: 70,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 21,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
    timer: 70,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 22,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
    ],
    timer: 50,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 23,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
    ],
    timer: 50,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 24,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
    timer: 50,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 25,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
    ],
    timer: 60,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 26,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
    ],
    timer: 60,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 27,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-1.jpg'),
      require('@/assets/images/questions/ancient/ancient-2.jpg'),
      require('@/assets/images/questions/ancient/ancient-3.jpg'),
      require('@/assets/images/questions/ancient/ancient-4.jpg'),
      require('@/assets/images/questions/ancient/ancient-5.jpg'),
      require('@/assets/images/questions/ancient/ancient-6.jpg'),
    ],
    timer: 60,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 28,
    theme: LevelTheme.Ancient,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/ancient/ancient-7.jpg'),
      require('@/assets/images/questions/ancient/ancient-8.jpg'),
      require('@/assets/images/questions/ancient/ancient-9.jpg'),
      require('@/assets/images/questions/ancient/ancient-10.jpg'),
      require('@/assets/images/questions/ancient/ancient-11.jpg'),
      require('@/assets/images/questions/ancient/ancient-12.jpg'),
    ],
    timer: 60,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
];