import { Level, LevelTheme, LevelType } from '@/models/Level';

export const animalThemeLevels: Level[] = [
  {
    id: 1,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 2,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 3,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 4,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 5,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 6,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 7,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
      require('@/assets/images/questions/animal/animal-41.svg'),
      require('@/assets/images/questions/animal/animal-42.svg'),
    ],
    timer: 40,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 8,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
    ],
    timer: 50,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 9,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
    ],
    timer: 50,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 10,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 50,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 11,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
    ],
    timer: 50,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 12,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 50,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 13,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
    ],
    timer: 50,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 14,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
    ],
    timer: 50,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 15,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 50,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 16,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 50,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 17,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
    ],
    timer: 80,
    star1Score: 360,
    star2Score: 540,
    star3Score: 720,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 18,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 80,
    star1Score: 360,
    star2Score: 540,
    star3Score: 720,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 19,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
    ],
    timer: 80,
    star1Score: 360,
    star2Score: 540,
    star3Score: 720,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 20,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
    ],
    timer: 100,
    star1Score: 450,
    star2Score: 675,
    star3Score: 900,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 21,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 100,
    star1Score: 450,
    star2Score: 675,
    star3Score: 900,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 22,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 23,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 24,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 25,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 26,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 27,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 28,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 29,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 30,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 31,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 32,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
    ],
    timer: 100,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 33,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
    ],
    timer: 100,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 34,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 100,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 35,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
    ],
    timer: 100,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 36,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 100,
    star1Score: 240,
    star2Score: 360,
    star3Score: 480,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 37,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
    ],
    timer: 100,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 38,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
    ],
    timer: 100,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 39,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 100,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 40,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 100,
    star1Score: 300,
    star2Score: 450,
    star3Score: 600,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 41,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 42,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 43,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 44,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 45,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 46,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 47,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 48,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 49,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 50,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 51,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 52,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 53,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 54,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-40.svg'),
      require('@/assets/images/questions/animal/animal-41.svg'),
      require('@/assets/images/questions/animal/animal-42.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 3,
  },
  {
    id: 55,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 56,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 57,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 58,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 59,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 60,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 61,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 62,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 63,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 64,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 65,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 100,
    star1Score: 90,
    star2Score: 135,
    star3Score: 180,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 66,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 67,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 68,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 69,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 70,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
      require('@/assets/images/questions/animal/animal-25.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 71,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 72,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 73,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-36.svg'),
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 74,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-36.svg'),
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 75,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 76,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 77,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 78,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 79,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 80,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 81,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
      require('@/assets/images/questions/animal/animal-41.svg'),
      require('@/assets/images/questions/animal/animal-42.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 82,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 83,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 84,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 85,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 86,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 87,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 88,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 89,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 90,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 91,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 100,
    star1Score: 120,
    star2Score: 180,
    star3Score: 240,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 4,
  },
  {
    id: 92,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 93,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 94,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 95,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 96,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
      require('@/assets/images/questions/animal/animal-25.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 97,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 98,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 99,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-36.svg'),
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
    ],
    timer: 100,
    star1Score: 150,
    star2Score: 225,
    star3Score: 300,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 100,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 101,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-7.svg'),
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 102,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 103,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 104,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 105,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
      require('@/assets/images/questions/animal/animal-36.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 106,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
      require('@/assets/images/questions/animal/animal-41.svg'),
      require('@/assets/images/questions/animal/animal-42.svg'),
    ],
    timer: 100,
    star1Score: 180,
    star2Score: 270,
    star3Score: 360,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 107,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-1.svg'),
      require('@/assets/images/questions/animal/animal-2.svg'),
      require('@/assets/images/questions/animal/animal-3.svg'),
      require('@/assets/images/questions/animal/animal-4.svg'),
      require('@/assets/images/questions/animal/animal-5.svg'),
      require('@/assets/images/questions/animal/animal-6.svg'),
      require('@/assets/images/questions/animal/animal-7.svg'),
    ],
    timer: 100,
    star1Score: 210,
    star2Score: 305,
    star3Score: 420,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 108,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-8.svg'),
      require('@/assets/images/questions/animal/animal-9.svg'),
      require('@/assets/images/questions/animal/animal-10.svg'),
      require('@/assets/images/questions/animal/animal-11.svg'),
      require('@/assets/images/questions/animal/animal-12.svg'),
      require('@/assets/images/questions/animal/animal-13.svg'),
      require('@/assets/images/questions/animal/animal-14.svg'),
    ],
    timer: 100,
    star1Score: 210,
    star2Score: 305,
    star3Score: 420,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 109,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-15.svg'),
      require('@/assets/images/questions/animal/animal-16.svg'),
      require('@/assets/images/questions/animal/animal-17.svg'),
      require('@/assets/images/questions/animal/animal-18.svg'),
      require('@/assets/images/questions/animal/animal-19.svg'),
      require('@/assets/images/questions/animal/animal-20.svg'),
      require('@/assets/images/questions/animal/animal-21.svg'),
    ],
    timer: 100,
    star1Score: 210,
    star2Score: 305,
    star3Score: 420,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 110,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-22.svg'),
      require('@/assets/images/questions/animal/animal-23.svg'),
      require('@/assets/images/questions/animal/animal-24.svg'),
      require('@/assets/images/questions/animal/animal-25.svg'),
      require('@/assets/images/questions/animal/animal-26.svg'),
      require('@/assets/images/questions/animal/animal-27.svg'),
      require('@/assets/images/questions/animal/animal-28.svg'),
    ],
    timer: 100,
    star1Score: 210,
    star2Score: 305,
    star3Score: 420,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 111,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-29.svg'),
      require('@/assets/images/questions/animal/animal-30.svg'),
      require('@/assets/images/questions/animal/animal-31.svg'),
      require('@/assets/images/questions/animal/animal-32.svg'),
      require('@/assets/images/questions/animal/animal-33.svg'),
      require('@/assets/images/questions/animal/animal-34.svg'),
      require('@/assets/images/questions/animal/animal-35.svg'),
    ],
    timer: 100,
    star1Score: 210,
    star2Score: 305,
    star3Score: 420,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
  {
    id: 112,
    theme: LevelTheme.Animal,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/animal/animal-36.svg'),
      require('@/assets/images/questions/animal/animal-37.svg'),
      require('@/assets/images/questions/animal/animal-38.svg'),
      require('@/assets/images/questions/animal/animal-39.svg'),
      require('@/assets/images/questions/animal/animal-40.svg'),
      require('@/assets/images/questions/animal/animal-41.svg'),
      require('@/assets/images/questions/animal/animal-42.svg'),
    ],
    timer: 100,
    star1Score: 210,
    star2Score: 305,
    star3Score: 420,
    star1Coins: 10,
    star2Coins: 30,
    star3Coins: 50,
    columns: 5,
  },
];
