import { LevelTheme, LevelType } from '@/models/Level';

export const cactusThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
      require('@/assets/images/questions/cactus/cactus-16.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
      require('@/assets/images/questions/cactus/cactus-16.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
      require('@/assets/images/questions/cactus/cactus-16.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
      require('@/assets/images/questions/cactus/cactus-16.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
      require('@/assets/images/questions/cactus/cactus-16.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/cactus/cactus-6.svg'),
      require('@/assets/images/questions/cactus/cactus-7.svg'),
      require('@/assets/images/questions/cactus/cactus-8.svg'),
      require('@/assets/images/questions/cactus/cactus-9.svg'),
      require('@/assets/images/questions/cactus/cactus-10.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/cactus/cactus-11.svg'),
      require('@/assets/images/questions/cactus/cactus-12.svg'),
      require('@/assets/images/questions/cactus/cactus-13.svg'),
      require('@/assets/images/questions/cactus/cactus-14.svg'),
      require('@/assets/images/questions/cactus/cactus-15.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.Cactus,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/cactus/cactus-1.svg'),
      require('@/assets/images/questions/cactus/cactus-2.svg'),
      require('@/assets/images/questions/cactus/cactus-3.svg'),
      require('@/assets/images/questions/cactus/cactus-4.svg'),
      require('@/assets/images/questions/cactus/cactus-5.svg'),
      require('@/assets/images/questions/cactus/cactus-6.svg'),
    ],
  },
]