import { LevelTheme, LevelType } from '@/models/Level';

export const chineseThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['忐', '忑', '忍', '念', '忘', '忽'],
  },
  {
    id: 2,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['於', '族', '旅', '施', '旋', '旗'],
  },
  {
    id: 3,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['欣', '歆', '次', '歐', '欶', '欲'],
  },
  {
    id: 4,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['戈', '戊', '成', '戎', '或', '戌'],
  },
  {
    id: 5,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['段', '殷', '殺', '股', '毆', '毅'],
  },
  {
    id: 6,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['母', '毋', '每', '毒', '毐', '毓'],
  },
  {
    id: 7,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['氖', '氙', '氛', '氟', '氣', '氮'],
  },
  {
    id: 8,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['版', '牉', '牌', '牒', '牓', '牘'],
  },
  {
    id: 9,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['盂', '盃', '盅', '益', '盒', '盛'],
  },
  {
    id: 10,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['知', '矩', '短', '矮', '矯', '矰'],
  },
  {
    id: 11,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['耔', '耙', '耗', '耕', '耘', '耡'],
  },
  {
    id: 12,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['臼', '臿', '舀', '舂', '與', '興'],
  },
  {
    id: 13,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['虎', '虐', '虔', '處', '虛', '虞', '虜', '虒'],
  },
  {
    id: 14,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['衎', '衍', '銜', '術', '衕', '街', '衙', '衝'],
  },
  {
    id: 15,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['袁', '衰', '衷', '袈', '裟', '製', '裂', '裘'],
  },
  {
    id: 16,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['規', '視', '覘', '親', '覦', '覬', '覲', '觀'],
  },
  {
    id: 17,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['觔', '觝', '觚', '觡', '解', '觸', '觰', '觴'],
  },
  {
    id: 18,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['豹', '狼', '豺', '貂', '貘', '貅', '狸', '貓'],
  },
  {
    id: 19,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['鼢', '鼥', '鼩', '鼫', '鼬', '鼮', '鼯', '鼴'],
  },
  {
    id: 20,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['勺', '刁', '勾', '勿', '勻', '包', '匆', '匈', '匋', '匊'],
  },
  {
    id: 21,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['元', '允', '兄', '充', '光', '兇', '免', '克', '兒', '兜'],
  },
  {
    id: 22,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['卯', '印', '卵', '即', '卲', '卸', '卻', '卿', '卬', '卹'],
  },
  {
    id: 23,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['韌', '韎', '韍', '韐', '韓', '韔', '韘', '韗', '韜', '韟'],
  },
  {
    id: 24,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['髦', '髣', '髴', '髲', '鬍', '髭', '髯', '鬚', '髮', '髻'],
  },
  {
    id: 25,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['颮', '颷', '颩', '颱', '颳', '颶', '颸', '颼', '颲', '颺'],
  },
  {
    id: 26,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['魁', '鬾', '魃', '魅', '魆', '魈', '魋', '魎', '魍', '魑'],
  },
  {
    id: 27,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['默', '黕', '黔', '點', '黜', '黚', '黠', '黟', '黯', '黥'],
  },
  {
    id: 28,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: ['森', '鑫', '毳', '焱', '矗', '磊', '聶', '蟲', '轟', '鱻'],
  },
  {
    id: 29,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: [
      '魠',
      '魟',
      '魴',
      '魨',
      '魦',
      '魷',
      '鮑',
      '鰒',
      '鮮',
      '鰓',
      '鮪',
      '鰭',
    ],
  },
  {
    id: 30,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: [
      '骭',
      '骰',
      '骯',
      '髒',
      '骷',
      '骼',
      '骸',
      '骹',
      '髁',
      '髂',
      '髓',
      '體',
    ],
  },
  {
    id: 31,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: [
      '慕',
      '幕',
      '墓',
      '募',
      '暮',
      '莫',
      '寞',
      '冪',
      '草',
      '漠',
      '驀',
      '幂',
    ],
  },
  {
    id: 32,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 2,
    questions: [
      '飯',
      '餛',
      '飩',
      '餅',
      '飲',
      '飢',
      '飽',
      '飾',
      '飼',
      '飴',
      '餃',
      '館',
    ],
  },
  {
    id: 33,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['弄', '弈', '弇', '弁'],
  },
  {
    id: 34,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['彤', '衫', '形', '彩'],
  },
  {
    id: 35,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['料', '斛', '斜', '斟'],
  },
  {
    id: 36,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['甩', '用', '甫', '甭'],
  },
  {
    id: 37,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['靖', '靚', '靛', '靜'],
  },
  {
    id: 38,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['鬧', '鬨', '鬩', '鬫'],
  },
  {
    id: 39,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['鬻', '鬺', '鬷', '鬵'],
  },
  {
    id: 40,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['鹹', '鹺', '鹼', '鹵'],
  },
  {
    id: 41,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['鳦', '鴃', '鵌', '䳘', '鴥', '鴕', '鵻', '鸃'],
  },
  {
    id: 42,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['鳶', '鴛', '鴷', '鵀', '鶿', '鷩', '鷺', '鷿'],
  },
  {
    id: 43,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['鵬', '鵩', '鵰', '鶆', '鶊', '鶄', '鵲', '鳳'],
  },
  {
    id: 44,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['麥', '麩', '麮', '麰', '䴸', '麴', '麵', '麪'],
  },
  {
    id: 45,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['黽', '黾', '黿', '鼂', '鼄', '鼇', '鼈', '鼉'],
  },
  {
    id: 46,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['齔', '齕', '齘', '齖', '齗', '齙', '齠', '齡', '齟', '齣'],
  },
  {
    id: 47,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['齦', '齜', '齪', '齬', '齯', '齰', '齱', '齮', '齲', '齵'],
  },
  {
    id: 48,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 3,
    questions: ['攷', '收', '改', '攻', '攸', '放', '故', '政', '敉', '效'],
  },
  {
    id: 49,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['廷', '延', '建'],
  },
  {
    id: 50,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['彔', '彖', '彙'],
  },
  {
    id: 51,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['氏', '民', '氐'],
  },
  {
    id: 52,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['甡', '生', '甥'],
  },
  {
    id: 53,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['耑', '耍', '耎'],
  },
  {
    id: 54,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['肄', '肆', '肇'],
  },
  {
    id: 55,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['肄', '肆', '肇'],
  },
  {
    id: 56,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['艴', '艵', '艷'],
  },
  {
    id: 57,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['谹', '谽', '豁', '谿'],
  },
  {
    id: 58,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['禺', '禹', '禼', '禽'],
  },
  {
    id: 59,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['爸', '爹', '㸙', '爺'],
  },
  {
    id: 60,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['教', '救', '啟', '啟'],
  },
  {
    id: 61,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['釆', '采', '釉', '釋'],
  },
  {
    id: 62,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['里', '重', '量', '釐'],
  },
  {
    id: 63,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['雪', '雩', '雱', '雰'],
  },
  {
    id: 64,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['麻', '麼', '麾', '黂'],
  },
  {
    id: 65,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['黍', '黎', '黏', '黐'],
  },
  {
    id: 66,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['鼎', '鼏', '鼐', '鼒'],
  },
  {
    id: 67,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['龍', '龑', '龔', '龕'],
  },
  {
    id: 68,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['雯', '雲', '雹', '雺', '電'],
  },
  {
    id: 69,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['敦', '敜', '敢', '敞', '散'],
  },
  {
    id: 70,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['靮', '靶', '靸', '靳', '靴'],
  },
  {
    id: 71,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['頂', '頄', '頃', '頇', '項'],
  },
  {
    id: 72,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['飣', '飢', '餑', '餔', '餕'],
  },
  {
    id: 73,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['馝', '馞', '馡', '馥', '馨'],
  },
  {
    id: 74,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['釜', '銎', '鋈', '鍪', '鎏'],
  },
  {
    id: 75,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['閃', '閉', '閈', '閆', '閔'],
  },
  {
    id: 76,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['隻', '隼', '集', '雋', '雀', '雇'],
  },
  {
    id: 77,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['躬', '躲', '䠷', '躺', '身', '軀'],
  },
  {
    id: 78,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['匹', '匼', '匽', '匾', '匿', '區'],
  },
  {
    id: 79,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['靿', '鞅', '鞜', '鞚', '鞠', '鞭'],
  },
  {
    id: 80,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['須', '順', '頒', '頓', '頍', '頏'],
  },
  {
    id: 81,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['釹', '鈦', '鈆', '鉧', '鉗', '銓'],
  },
  {
    id: 82,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 4,
    questions: ['赧', '赦', '赨', '赩', '赫', '䞓'],
  },
  {
    id: 83,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['雷', '零', '需', '霈'],
  },
  {
    id: 84,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['匝', '匜', '匟', '匡'],
  },
  {
    id: 85,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['辦', '辨', '辭', '辯'],
  },
  {
    id: 86,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['缸', '缺', '缽', '缾'],
  },
  {
    id: 87,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['羈', '羇', '羅', '羆'],
  },
  {
    id: 88,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['羌', '羑', '羔', '羕'],
  },
  {
    id: 89,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['翻', '翹', '翽', '翾'],
  },
  {
    id: 90,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['耶', '耵', '耽', '耿'],
  },
  {
    id: 91,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['肝', '肚', '肌', '肋'],
  },
  {
    id: 92,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['艾', '芏', '芐', '芣'],
  },
  {
    id: 93,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['餱', '餬', '餭', '餲', '餵'],
  },
  {
    id: 94,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['頊', '頌', '頑', '預', '預'],
  },
  {
    id: 95,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['開', '閌', '閎', '間', '閒'],
  },
  {
    id: 96,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['聃', '聊', '聆', '聒', '聐'],
  },
  {
    id: 97,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['朋', '棘', '林', '皕', '䲆', '龖'],
  },
  {
    id: 98,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['㒭', '槑', '踀', '䣈', '𣊫', '喆'],
  },
  {
    id: 99,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['隹', '雔', '雥', '又', '双', '叒'],
  },
  {
    id: 100,
    theme: LevelTheme.ChineseWord,
    type: LevelType.String,
    matchCount: 5,
    questions: ['石', '砳', '磊', '牛', '牪', '犇'],
  },
];
