import { LevelTheme, LevelType } from '@/models/Level';

export const cityBuildingThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
      require('@/assets/images/questions/city-building/city-building-29.svg'),
      require('@/assets/images/questions/city-building/city-building-30.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
      require('@/assets/images/questions/city-building/city-building-29.svg'),
      require('@/assets/images/questions/city-building/city-building-30.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
      require('@/assets/images/questions/city-building/city-building-29.svg'),
      require('@/assets/images/questions/city-building/city-building-30.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
      require('@/assets/images/questions/city-building/city-building-29.svg'),
      require('@/assets/images/questions/city-building/city-building-30.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
      require('@/assets/images/questions/city-building/city-building-21.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-28.svg'),
      require('@/assets/images/questions/city-building/city-building-29.svg'),
      require('@/assets/images/questions/city-building/city-building-30.svg'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
    ],
  },
  {
    id: 41,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
    ],
  },
  {
    id: 42,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
    ],
  },
  {
    id: 43,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
    ],
  },
  {
    id: 44,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 45,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
    ],
  },
  {
    id: 46,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
    ],
  },
  {
    id: 47,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
    ],
  },
  {
    id: 48,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
    ],
  },
  {
    id: 49,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
    ],
  },
  {
    id: 50,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
      require('@/assets/images/questions/city-building/city-building-25.svg'),
    ],
  },
  {
    id: 51,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
      require('@/assets/images/questions/city-building/city-building-29.svg'),
      require('@/assets/images/questions/city-building/city-building-30.svg'),
    ],
  },
  {
    id: 52,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
    ],
  },
  {
    id: 53,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
    ],
  },
  {
    id: 54,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
    ],
  },
  {
    id: 55,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 56,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
      require('@/assets/images/questions/city-building/city-building-29.svg'),
      require('@/assets/images/questions/city-building/city-building-30.svg'),
    ],
  },
  {
    id: 57,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
    ],
  },
  {
    id: 58,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
    ],
  },
  {
    id: 59,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
    ],
  },
  {
    id: 60,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
    ],
  },
  {
    id: 61,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
    ],
  },
  {
    id: 62,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
    ],
  },
  {
    id: 63,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-25.svg'),
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
    ],
  },
  {
    id: 64,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
    ],
  },
  {
    id: 65,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-6.svg'),
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
    ],
  },
  {
    id: 66,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
    ],
  },
  {
    id: 67,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
      require('@/assets/images/questions/city-building/city-building-19.svg'),
      require('@/assets/images/questions/city-building/city-building-20.svg'),
    ],
  },
  {
    id: 68,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-21.svg'),
      require('@/assets/images/questions/city-building/city-building-22.svg'),
      require('@/assets/images/questions/city-building/city-building-23.svg'),
      require('@/assets/images/questions/city-building/city-building-24.svg'),
      require('@/assets/images/questions/city-building/city-building-25.svg'),
    ],
  },
  {
    id: 69,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-26.svg'),
      require('@/assets/images/questions/city-building/city-building-27.svg'),
      require('@/assets/images/questions/city-building/city-building-28.svg'),
      require('@/assets/images/questions/city-building/city-building-29.svg'),
      require('@/assets/images/questions/city-building/city-building-30.svg'),
    ],
  },
  {
    id: 70,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-1.svg'),
      require('@/assets/images/questions/city-building/city-building-2.svg'),
      require('@/assets/images/questions/city-building/city-building-3.svg'),
      require('@/assets/images/questions/city-building/city-building-4.svg'),
      require('@/assets/images/questions/city-building/city-building-5.svg'),
      require('@/assets/images/questions/city-building/city-building-6.svg'),
    ],
  },
  {
    id: 71,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-7.svg'),
      require('@/assets/images/questions/city-building/city-building-8.svg'),
      require('@/assets/images/questions/city-building/city-building-9.svg'),
      require('@/assets/images/questions/city-building/city-building-10.svg'),
      require('@/assets/images/questions/city-building/city-building-11.svg'),
      require('@/assets/images/questions/city-building/city-building-12.svg'),
    ],
  },
  {
    id: 72,
    theme: LevelTheme.CityBuilding,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/city-building/city-building-13.svg'),
      require('@/assets/images/questions/city-building/city-building-14.svg'),
      require('@/assets/images/questions/city-building/city-building-15.svg'),
      require('@/assets/images/questions/city-building/city-building-16.svg'),
      require('@/assets/images/questions/city-building/city-building-17.svg'),
      require('@/assets/images/questions/city-building/city-building-18.svg'),
    ],
  },
];
