import { LevelTheme, LevelType } from '@/models/Level';

export const gesturesThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
      require('@/assets/images/questions/gestures/gestures-49.svg'),
      require('@/assets/images/questions/gestures/gestures-50.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
    ],
  },
  {
    id: 41,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 42,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
    ],
  },
  {
    id: 43,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 44,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 45,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
    ],
  },
  {
    id: 46,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
    ],
  },
  {
    id: 47,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 48,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 49,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
      require('@/assets/images/questions/gestures/gestures-49.svg'),
      require('@/assets/images/questions/gestures/gestures-50.svg'),
    ],
  },
  {
    id: 50,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
    ],
  },
  {
    id: 51,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
    ],
  },
  {
    id: 52,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
    ],
  },
  {
    id: 53,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
    ],
  },
  {
    id: 54,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
    ],
  },
  {
    id: 55,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
    ],
  },
  {
    id: 56,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
    ],
  },
  {
    id: 57,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 58,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
    ],
  },
  {
    id: 59,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 60,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
    ],
  },
  {
    id: 61,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
    ],
  },
  {
    id: 62,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
    ],
  },
  {
    id: 63,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-40.svg'),
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
    ],
  },
  {
    id: 64,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
    ],
  },
  {
    id: 65,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 66,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
    ],
  },
  {
    id: 67,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
    ],
  },
  {
    id: 68,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
    ],
  },
  {
    id: 69,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
    ],
  },
  {
    id: 70,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
    ],
  },
  {
    id: 71,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 72,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
    ],
  },
  {
    id: 73,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
    ],
  },
  {
    id: 74,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
    ],
  },
  {
    id: 75,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 76,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
    ],
  },
  {
    id: 77,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 78,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
    ],
  },
  {
    id: 79,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
    ],
  },
  {
    id: 80,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
    ],
  },
  {
    id: 81,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
    ],
  },
  {
    id: 82,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
      require('@/assets/images/questions/gestures/gestures-25.svg'),
    ],
  },
  {
    id: 83,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 84,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
    ],
  },
  {
    id: 85,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-36.svg'),
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 86,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
    ],
  },
  {
    id: 87,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
      require('@/assets/images/questions/gestures/gestures-49.svg'),
      require('@/assets/images/questions/gestures/gestures-50.svg'),
    ],
  },
  {
    id: 88,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
    ],
  },
  {
    id: 89,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
    ],
  },
  {
    id: 90,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
    ],
  },
  {
    id: 91,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 92,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 93,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
    ],
  },
  {
    id: 94,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
    ],
  },
  {
    id: 95,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 96,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
    ],
  },
  {
    id: 97,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
    ],
  },
  {
    id: 98,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
    ],
  },
  {
    id: 99,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
    ],
  },
  {
    id: 100,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
    ],
  },
  {
    id: 101,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 102,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
    ],
  },
  {
    id: 103,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
    ],
  },
  {
    id: 104,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
    ],
  },
  {
    id: 105,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 106,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
    ],
  },
  {
    id: 107,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 108,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
    ],
  },
  {
    id: 109,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
    ],
  },
  {
    id: 110,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
    ],
  },
  {
    id: 111,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
    ],
  },
  {
    id: 112,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
      require('@/assets/images/questions/gestures/gestures-25.svg'),
    ],
  },
  {
    id: 113,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 114,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
    ],
  },
  {
    id: 115,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-36.svg'),
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
    ],
  },
  {
    id: 116,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
    ],
  },
  {
    id: 117,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
      require('@/assets/images/questions/gestures/gestures-49.svg'),
      require('@/assets/images/questions/gestures/gestures-50.svg'),
    ],
  },
  {
    id: 118,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
    ],
  },
  {
    id: 119,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-7.svg'),
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
    ],
  },
  {
    id: 120,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
    ],
  },
  {
    id: 121,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
    ],
  },
  {
    id: 122,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
    ],
  },
  {
    id: 123,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
      require('@/assets/images/questions/gestures/gestures-36.svg'),
    ],
  },
  {
    id: 124,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
    ],
  },
  {
    id: 125,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
    ],
  },
  {
    id: 126,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-1.svg'),
      require('@/assets/images/questions/gestures/gestures-2.svg'),
      require('@/assets/images/questions/gestures/gestures-3.svg'),
      require('@/assets/images/questions/gestures/gestures-4.svg'),
      require('@/assets/images/questions/gestures/gestures-5.svg'),
      require('@/assets/images/questions/gestures/gestures-6.svg'),
      require('@/assets/images/questions/gestures/gestures-7.svg'),
    ],
  },
  {
    id: 127,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-8.svg'),
      require('@/assets/images/questions/gestures/gestures-9.svg'),
      require('@/assets/images/questions/gestures/gestures-10.svg'),
      require('@/assets/images/questions/gestures/gestures-11.svg'),
      require('@/assets/images/questions/gestures/gestures-12.svg'),
      require('@/assets/images/questions/gestures/gestures-13.svg'),
      require('@/assets/images/questions/gestures/gestures-14.svg'),
    ],
  },
  {
    id: 128,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-15.svg'),
      require('@/assets/images/questions/gestures/gestures-16.svg'),
      require('@/assets/images/questions/gestures/gestures-17.svg'),
      require('@/assets/images/questions/gestures/gestures-18.svg'),
      require('@/assets/images/questions/gestures/gestures-19.svg'),
      require('@/assets/images/questions/gestures/gestures-20.svg'),
      require('@/assets/images/questions/gestures/gestures-21.svg'),
    ],
  },
  {
    id: 129,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-22.svg'),
      require('@/assets/images/questions/gestures/gestures-23.svg'),
      require('@/assets/images/questions/gestures/gestures-24.svg'),
      require('@/assets/images/questions/gestures/gestures-25.svg'),
      require('@/assets/images/questions/gestures/gestures-26.svg'),
      require('@/assets/images/questions/gestures/gestures-27.svg'),
      require('@/assets/images/questions/gestures/gestures-28.svg'),
    ],
  },
  {
    id: 130,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-29.svg'),
      require('@/assets/images/questions/gestures/gestures-30.svg'),
      require('@/assets/images/questions/gestures/gestures-31.svg'),
      require('@/assets/images/questions/gestures/gestures-32.svg'),
      require('@/assets/images/questions/gestures/gestures-33.svg'),
      require('@/assets/images/questions/gestures/gestures-34.svg'),
      require('@/assets/images/questions/gestures/gestures-35.svg'),
    ],
  },
  {
    id: 131,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-36.svg'),
      require('@/assets/images/questions/gestures/gestures-37.svg'),
      require('@/assets/images/questions/gestures/gestures-38.svg'),
      require('@/assets/images/questions/gestures/gestures-39.svg'),
      require('@/assets/images/questions/gestures/gestures-40.svg'),
      require('@/assets/images/questions/gestures/gestures-41.svg'),
      require('@/assets/images/questions/gestures/gestures-42.svg'),
    ],
  },
  {
    id: 132,
    theme: LevelTheme.Gestures,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gestures/gestures-43.svg'),
      require('@/assets/images/questions/gestures/gestures-44.svg'),
      require('@/assets/images/questions/gestures/gestures-45.svg'),
      require('@/assets/images/questions/gestures/gestures-46.svg'),
      require('@/assets/images/questions/gestures/gestures-47.svg'),
      require('@/assets/images/questions/gestures/gestures-48.svg'),
      require('@/assets/images/questions/gestures/gestures-49.svg'),
    ],
  },
];
