import { LevelTheme, LevelType } from '@/models/Level';

export const giftThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
      require('@/assets/images/questions/gift/gift-16.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
      require('@/assets/images/questions/gift/gift-16.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
      require('@/assets/images/questions/gift/gift-16.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
      require('@/assets/images/questions/gift/gift-16.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
      require('@/assets/images/questions/gift/gift-16.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gift/gift-6.svg'),
      require('@/assets/images/questions/gift/gift-7.svg'),
      require('@/assets/images/questions/gift/gift-8.svg'),
      require('@/assets/images/questions/gift/gift-9.svg'),
      require('@/assets/images/questions/gift/gift-10.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gift/gift-11.svg'),
      require('@/assets/images/questions/gift/gift-12.svg'),
      require('@/assets/images/questions/gift/gift-13.svg'),
      require('@/assets/images/questions/gift/gift-14.svg'),
      require('@/assets/images/questions/gift/gift-15.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.Gift,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/gift/gift-1.svg'),
      require('@/assets/images/questions/gift/gift-2.svg'),
      require('@/assets/images/questions/gift/gift-3.svg'),
      require('@/assets/images/questions/gift/gift-4.svg'),
      require('@/assets/images/questions/gift/gift-5.svg'),
      require('@/assets/images/questions/gift/gift-6.svg'),
    ],
  },
];
