import { LevelTheme, LevelType } from '@/models/Level';

export const grassThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
      require('@/assets/images/questions/grass/grass-16.png'),
      require('@/assets/images/questions/grass/grass-17.png'),
      require('@/assets/images/questions/grass/grass-18.png'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
      require('@/assets/images/questions/grass/grass-16.png'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
      require('@/assets/images/questions/grass/grass-16.png'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
      require('@/assets/images/questions/grass/grass-16.png'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-16.png'),
      require('@/assets/images/questions/grass/grass-17.png'),
      require('@/assets/images/questions/grass/grass-18.png'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
      require('@/assets/images/questions/grass/grass-16.png'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
      require('@/assets/images/questions/grass/grass-16.png'),
      require('@/assets/images/questions/grass/grass-17.png'),
      require('@/assets/images/questions/grass/grass-18.png'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
      require('@/assets/images/questions/grass/grass-16.png'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-6.png'),
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
      require('@/assets/images/questions/grass/grass-13.png'),
      require('@/assets/images/questions/grass/grass-14.png'),
      require('@/assets/images/questions/grass/grass-15.png'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-1.png'),
      require('@/assets/images/questions/grass/grass-2.png'),
      require('@/assets/images/questions/grass/grass-3.png'),
      require('@/assets/images/questions/grass/grass-4.png'),
      require('@/assets/images/questions/grass/grass-5.png'),
      require('@/assets/images/questions/grass/grass-6.png'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.Grass,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/grass/grass-7.png'),
      require('@/assets/images/questions/grass/grass-8.png'),
      require('@/assets/images/questions/grass/grass-9.png'),
      require('@/assets/images/questions/grass/grass-10.png'),
      require('@/assets/images/questions/grass/grass-11.png'),
      require('@/assets/images/questions/grass/grass-12.png'),
    ],
  },
];
