import { LevelTheme, LevelType } from '@/models/Level';

export const leaveThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
      require('@/assets/images/questions/leave/leave-31.svg'),
      require('@/assets/images/questions/leave/leave-32.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
      require('@/assets/images/questions/leave/leave-31.svg'),
      require('@/assets/images/questions/leave/leave-32.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
      require('@/assets/images/questions/leave/leave-31.svg'),
      require('@/assets/images/questions/leave/leave-32.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
    ],
  },
  {
    id: 41,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 42,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
    ],
  },
  {
    id: 43,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
    ],
  },
  {
    id: 44,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
    ],
  },
  {
    id: 45,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
    ],
  },
  {
    id: 46,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
    ],
  },
  {
    id: 47,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 48,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
    ],
  },
  {
    id: 49,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
      require('@/assets/images/questions/leave/leave-31.svg'),
      require('@/assets/images/questions/leave/leave-32.svg'),
    ],
  },
  {
    id: 50,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
    ],
  },
  {
    id: 51,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
    ],
  },
  {
    id: 52,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
    ],
  },
  {
    id: 53,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
    ],
  },
  {
    id: 54,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
      require('@/assets/images/questions/leave/leave-25.svg'),
    ],
  },
  {
    id: 55,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 56,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 57,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
    ],
  },
  {
    id: 58,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
    ],
  },
  {
    id: 59,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
    ],
  },
  {
    id: 60,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 61,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 62,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
    ],
  },
  {
    id: 63,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
    ],
  },
  {
    id: 64,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
    ],
  },
  {
    id: 65,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
    ],
  },
  {
    id: 66,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
    ],
  },
  {
    id: 67,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 68,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
    ],
  },
  {
    id: 69,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
      require('@/assets/images/questions/leave/leave-31.svg'),
      require('@/assets/images/questions/leave/leave-32.svg'),
    ],
  },
  {
    id: 70,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
    ],
  },
  {
    id: 71,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
    ],
  },
  {
    id: 72,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
    ],
  },
  {
    id: 73,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
    ],
  },
  {
    id: 74,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
      require('@/assets/images/questions/leave/leave-25.svg'),
    ],
  },
  {
    id: 75,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 76,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 77,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
    ],
  },
  {
    id: 78,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-7.svg'),
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
    ],
  },
  {
    id: 79,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
    ],
  },
  {
    id: 80,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
      require('@/assets/images/questions/leave/leave-22.svg'),
      require('@/assets/images/questions/leave/leave-23.svg'),
      require('@/assets/images/questions/leave/leave-24.svg'),
    ],
  },
  {
    id: 81,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-25.svg'),
      require('@/assets/images/questions/leave/leave-26.svg'),
      require('@/assets/images/questions/leave/leave-27.svg'),
      require('@/assets/images/questions/leave/leave-28.svg'),
      require('@/assets/images/questions/leave/leave-29.svg'),
      require('@/assets/images/questions/leave/leave-30.svg'),
    ],
  },
  {
    id: 82,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-1.svg'),
      require('@/assets/images/questions/leave/leave-2.svg'),
      require('@/assets/images/questions/leave/leave-3.svg'),
      require('@/assets/images/questions/leave/leave-4.svg'),
      require('@/assets/images/questions/leave/leave-5.svg'),
      require('@/assets/images/questions/leave/leave-6.svg'),
      require('@/assets/images/questions/leave/leave-7.svg'),
    ],
  },
  {
    id: 83,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-8.svg'),
      require('@/assets/images/questions/leave/leave-9.svg'),
      require('@/assets/images/questions/leave/leave-10.svg'),
      require('@/assets/images/questions/leave/leave-11.svg'),
      require('@/assets/images/questions/leave/leave-12.svg'),
      require('@/assets/images/questions/leave/leave-13.svg'),
      require('@/assets/images/questions/leave/leave-14.svg'),
    ],
  },
  {
    id: 84,
    theme: LevelTheme.Leaves,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/leave/leave-15.svg'),
      require('@/assets/images/questions/leave/leave-16.svg'),
      require('@/assets/images/questions/leave/leave-17.svg'),
      require('@/assets/images/questions/leave/leave-18.svg'),
      require('@/assets/images/questions/leave/leave-19.svg'),
      require('@/assets/images/questions/leave/leave-20.svg'),
      require('@/assets/images/questions/leave/leave-21.svg'),
    ],
  },
];
