import { LevelTheme, LevelType } from '@/models/Level';

export const noticeThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
    ],
  },
  {
    id: 41,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
    ],
  },
  {
    id: 42,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
    ],
  },
  {
    id: 43,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
    ],
  },
  {
    id: 44,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
    ],
  },
  {
    id: 45,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
    ],
  },
  {
    id: 46,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
      require('@/assets/images/questions/notice/notice-21.svg'),
    ],
  },
  {
    id: 47,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 48,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
    ],
  },
  {
    id: 49,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 50,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
    ],
  },
  {
    id: 51,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
    ],
  },
  {
    id: 52,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
    ],
  },
  {
    id: 53,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
    ],
  },
  {
    id: 54,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
    ],
  },
  {
    id: 55,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
    ],
  },
  {
    id: 56,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
    ],
  },
  {
    id: 57,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
    ],
  },
  {
    id: 58,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 59,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
    ],
  },
  {
    id: 60,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
    ],
  },
  {
    id: 61,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
    ],
  },
  {
    id: 62,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 63,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
    ],
  },
  {
    id: 64,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
    ],
  },
  {
    id: 65,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
    ],
  },
  {
    id: 66,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
    ],
  },
  {
    id: 67,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
      require('@/assets/images/questions/notice/notice-25.svg'),
    ],
  },
  {
    id: 68,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 69,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
    ],
  },
  {
    id: 70,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-36.svg'),
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 71,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
    ],
  },
  {
    id: 72,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
    ],
  },
  {
    id: 73,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
    ],
  },
  {
    id: 74,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 75,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 76,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
    ],
  },
  {
    id: 77,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
    ],
  },
  {
    id: 78,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
    ],
  },
  {
    id: 79,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
    ],
  },
  {
    id: 80,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
    ],
  },
  {
    id: 81,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
    ],
  },
  {
    id: 82,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 83,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
    ],
  },
  {
    id: 84,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
    ],
  },
  {
    id: 85,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
    ],
  },
  {
    id: 86,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 87,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
    ],
  },
  {
    id: 88,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-6.svg'),
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
    ],
  },
  {
    id: 89,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
    ],
  },
  {
    id: 90,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
    ],
  },
  {
    id: 91,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
      require('@/assets/images/questions/notice/notice-25.svg'),
    ],
  },
  {
    id: 92,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 93,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
    ],
  },
  {
    id: 94,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-36.svg'),
      require('@/assets/images/questions/notice/notice-37.svg'),
      require('@/assets/images/questions/notice/notice-38.svg'),
      require('@/assets/images/questions/notice/notice-39.svg'),
      require('@/assets/images/questions/notice/notice-40.svg'),
    ],
  },
  {
    id: 95,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-1.svg'),
      require('@/assets/images/questions/notice/notice-2.svg'),
      require('@/assets/images/questions/notice/notice-3.svg'),
      require('@/assets/images/questions/notice/notice-4.svg'),
      require('@/assets/images/questions/notice/notice-5.svg'),
      require('@/assets/images/questions/notice/notice-6.svg'),
    ],
  },
  {
    id: 96,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-7.svg'),
      require('@/assets/images/questions/notice/notice-8.svg'),
      require('@/assets/images/questions/notice/notice-9.svg'),
      require('@/assets/images/questions/notice/notice-10.svg'),
      require('@/assets/images/questions/notice/notice-11.svg'),
      require('@/assets/images/questions/notice/notice-12.svg'),
    ],
  },
  {
    id: 97,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-13.svg'),
      require('@/assets/images/questions/notice/notice-14.svg'),
      require('@/assets/images/questions/notice/notice-15.svg'),
      require('@/assets/images/questions/notice/notice-16.svg'),
      require('@/assets/images/questions/notice/notice-17.svg'),
      require('@/assets/images/questions/notice/notice-18.svg'),
    ],
  },
  {
    id: 98,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-19.svg'),
      require('@/assets/images/questions/notice/notice-20.svg'),
      require('@/assets/images/questions/notice/notice-21.svg'),
      require('@/assets/images/questions/notice/notice-22.svg'),
      require('@/assets/images/questions/notice/notice-23.svg'),
      require('@/assets/images/questions/notice/notice-24.svg'),
    ],
  },
  {
    id: 99,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-25.svg'),
      require('@/assets/images/questions/notice/notice-26.svg'),
      require('@/assets/images/questions/notice/notice-27.svg'),
      require('@/assets/images/questions/notice/notice-28.svg'),
      require('@/assets/images/questions/notice/notice-29.svg'),
      require('@/assets/images/questions/notice/notice-30.svg'),
    ],
  },
  {
    id: 100,
    theme: LevelTheme.Notice,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/notice/notice-31.svg'),
      require('@/assets/images/questions/notice/notice-32.svg'),
      require('@/assets/images/questions/notice/notice-33.svg'),
      require('@/assets/images/questions/notice/notice-34.svg'),
      require('@/assets/images/questions/notice/notice-35.svg'),
      require('@/assets/images/questions/notice/notice-36.svg'),
    ],
  },
];
