import { LevelTheme, LevelType } from '@/models/Level';

export const smartWatchThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
    ],
  },
  {
    id: 41,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
    ],
  },
  {
    id: 42,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
    ],
  },
  {
    id: 43,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
    ],
  },
  {
    id: 44,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
    ],
  },
  {
    id: 45,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
    ],
  },
  {
    id: 46,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
    ],
  },
  {
    id: 47,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 48,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
    ],
  },
  {
    id: 49,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 50,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
    ],
  },
  {
    id: 51,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
    ],
  },
  {
    id: 52,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
    ],
  },
  {
    id: 53,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
    ],
  },
  {
    id: 54,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
    ],
  },
  {
    id: 55,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
    ],
  },
  {
    id: 56,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
    ],
  },
  {
    id: 57,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
    ],
  },
  {
    id: 58,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 59,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
    ],
  },
  {
    id: 60,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
    ],
  },
  {
    id: 61,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
    ],
  },
  {
    id: 62,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 63,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
    ],
  },
  {
    id: 64,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
    ],
  },
  {
    id: 65,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
    ],
  },
  {
    id: 66,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
    ],
  },
  {
    id: 67,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
    ],
  },
  {
    id: 68,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 69,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
    ],
  },
  {
    id: 70,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 71,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
    ],
  },
  {
    id: 72,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
    ],
  },
  {
    id: 73,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
    ],
  },
  {
    id: 74,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 75,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 76,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
    ],
  },
  {
    id: 77,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
    ],
  },
  {
    id: 78,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
    ],
  },
  {
    id: 79,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
    ],
  },
  {
    id: 80,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
    ],
  },
  {
    id: 81,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
    ],
  },
  {
    id: 82,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 83,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
    ],
  },
  {
    id: 84,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
    ],
  },
  {
    id: 85,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
    ],
  },
  {
    id: 86,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 87,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
    ],
  },
  {
    id: 88,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
    ],
  },
  {
    id: 89,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
    ],
  },
  {
    id: 90,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
    ],
  },
  {
    id: 91,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
    ],
  },
  {
    id: 92,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 93,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
    ],
  },
  {
    id: 94,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-37.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-38.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-39.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-40.svg'),
    ],
  },
  {
    id: 95,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-1.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-2.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-3.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-4.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-5.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-6.svg'),
    ],
  },
  {
    id: 96,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-7.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-8.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-9.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-10.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-11.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-12.svg'),
    ],
  },
  {
    id: 97,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-13.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-14.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-15.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-16.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-17.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-18.svg'),
    ],
  },
  {
    id: 98,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-19.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-20.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-21.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-22.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-23.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-24.svg'),
    ],
  },
  {
    id: 99,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-25.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-26.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-27.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-28.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-29.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-30.svg'),
    ],
  },
  {
    id: 100,
    theme: LevelTheme.SmartWatch,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/smart-watch/smart-watch-31.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-32.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-33.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-34.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-35.svg'),
      require('@/assets/images/questions/smart-watch/smart-watch-36.svg'),
    ],
  },
];
