import { LevelTheme, LevelType } from '@/models/Level';

export const treeThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
      require('@/assets/images/questions/tree/tree-21.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
    ],
  },
  {
    id: 41,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
    ],
  },
  {
    id: 42,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
    ],
  },
  {
    id: 43,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
    ],
  },
  {
    id: 44,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
    ],
  },
  {
    id: 45,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
    ],
  },
  {
    id: 46,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
    ],
  },
  {
    id: 47,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
    ],
  },
  {
    id: 48,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-7.svg'),
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
    ],
  },
  {
    id: 49,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
    ],
  },
  {
    id: 50,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-1.svg'),
      require('@/assets/images/questions/tree/tree-2.svg'),
      require('@/assets/images/questions/tree/tree-3.svg'),
      require('@/assets/images/questions/tree/tree-4.svg'),
      require('@/assets/images/questions/tree/tree-5.svg'),
      require('@/assets/images/questions/tree/tree-6.svg'),
      require('@/assets/images/questions/tree/tree-7.svg'),
    ],
  },
  {
    id: 51,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-8.svg'),
      require('@/assets/images/questions/tree/tree-9.svg'),
      require('@/assets/images/questions/tree/tree-10.svg'),
      require('@/assets/images/questions/tree/tree-11.svg'),
      require('@/assets/images/questions/tree/tree-12.svg'),
      require('@/assets/images/questions/tree/tree-13.svg'),
      require('@/assets/images/questions/tree/tree-14.svg'),
    ],
  },
  {
    id: 52,
    theme: LevelTheme.Tree,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/tree/tree-15.svg'),
      require('@/assets/images/questions/tree/tree-16.svg'),
      require('@/assets/images/questions/tree/tree-17.svg'),
      require('@/assets/images/questions/tree/tree-18.svg'),
      require('@/assets/images/questions/tree/tree-19.svg'),
      require('@/assets/images/questions/tree/tree-20.svg'),
      require('@/assets/images/questions/tree/tree-21.svg'),
    ],
  },
];
