import { LevelTheme, LevelType } from '@/models/Level';

export const waterSportThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
    ],
  },
  {
    id: 41,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
    ],
  },
  {
    id: 42,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
    ],
  },
  {
    id: 43,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
    ],
  },
  {
    id: 44,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
    ],
  },
  {
    id: 45,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 46,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
    ],
  },
  {
    id: 47,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
    ],
  },
  {
    id: 48,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
    ],
  },
  {
    id: 49,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
    ],
  },
  {
    id: 50,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
    ],
  },
  {
    id: 51,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 52,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
    ],
  },
  {
    id: 53,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
    ],
  },
  {
    id: 54,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
    ],
  },
  {
    id: 55,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
    ],
  },
  {
    id: 56,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
    ],
  },
  {
    id: 57,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
      require('@/assets/images/questions/water-sport/water-sport-8.svg'),
      require('@/assets/images/questions/water-sport/water-sport-9.svg'),
      require('@/assets/images/questions/water-sport/water-sport-10.svg'),
      require('@/assets/images/questions/water-sport/water-sport-11.svg'),
      require('@/assets/images/questions/water-sport/water-sport-12.svg'),
    ],
  },
  {
    id: 58,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-13.svg'),
      require('@/assets/images/questions/water-sport/water-sport-14.svg'),
      require('@/assets/images/questions/water-sport/water-sport-15.svg'),
      require('@/assets/images/questions/water-sport/water-sport-16.svg'),
      require('@/assets/images/questions/water-sport/water-sport-17.svg'),
      require('@/assets/images/questions/water-sport/water-sport-18.svg'),
    ],
  },
  {
    id: 59,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-19.svg'),
      require('@/assets/images/questions/water-sport/water-sport-20.svg'),
      require('@/assets/images/questions/water-sport/water-sport-21.svg'),
      require('@/assets/images/questions/water-sport/water-sport-22.svg'),
      require('@/assets/images/questions/water-sport/water-sport-23.svg'),
      require('@/assets/images/questions/water-sport/water-sport-24.svg'),
    ],
  },
  {
    id: 60,
    theme: LevelTheme.WaterSport,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/water-sport/water-sport-1.svg'),
      require('@/assets/images/questions/water-sport/water-sport-2.svg'),
      require('@/assets/images/questions/water-sport/water-sport-3.svg'),
      require('@/assets/images/questions/water-sport/water-sport-4.svg'),
      require('@/assets/images/questions/water-sport/water-sport-5.svg'),
      require('@/assets/images/questions/water-sport/water-sport-6.svg'),
      require('@/assets/images/questions/water-sport/water-sport-7.svg'),
    ],
  },
];
