import { LevelTheme, LevelType } from '@/models/Level';

export const weatherThemeLevels = [
  {
    id: 1,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
    ],
  },
  {
    id: 2,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
    ],
  },
  {
    id: 3,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
    ],
  },
  {
    id: 4,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
    ],
  },
  {
    id: 5,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
    ],
  },
  {
    id: 6,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
    ],
  },
  {
    id: 7,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
      require('@/assets/images/questions/weather/weather-19.svg'),
      require('@/assets/images/questions/weather/weather-20.svg'),
    ],
  },
  {
    id: 8,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
    ],
  },
  {
    id: 9,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 2,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
    ],
  },
  {
    id: 10,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
    ],
  },
  {
    id: 11,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
    ],
  },
  {
    id: 12,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
    ],
  },
  {
    id: 13,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
    ],
  },
  {
    id: 14,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
      require('@/assets/images/questions/weather/weather-19.svg'),
      require('@/assets/images/questions/weather/weather-20.svg'),
    ],
  },
  {
    id: 15,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
    ],
  },
  {
    id: 16,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
    ],
  },
  {
    id: 17,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
    ],
  },
  {
    id: 18,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 3,
    questions: [
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
      require('@/assets/images/questions/weather/weather-19.svg'),
      require('@/assets/images/questions/weather/weather-20.svg'),
    ],
  },
  {
    id: 19,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
    ],
  },
  {
    id: 20,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
    ],
  },
  {
    id: 21,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
    ],
  },
  {
    id: 22,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
    ],
  },
  {
    id: 23,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
    ],
  },
  {
    id: 24,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-16.svg'),
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
    ],
  },
  {
    id: 25,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
    ],
  },
  {
    id: 26,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
    ],
  },
  {
    id: 27,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
    ],
  },
  {
    id: 28,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
    ],
  },
  {
    id: 29,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
      require('@/assets/images/questions/weather/weather-19.svg'),
      require('@/assets/images/questions/weather/weather-20.svg'),
    ],
  },
  {
    id: 30,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
    ],
  },
  {
    id: 31,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
    ],
  },
  {
    id: 32,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
    ],
  },
  {
    id: 33,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-16.svg'),
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
      require('@/assets/images/questions/weather/weather-19.svg'),
      require('@/assets/images/questions/weather/weather-20.svg'),
    ],
  },
  {
    id: 34,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
    ],
  },
  {
    id: 35,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
    ],
  },
  {
    id: 36,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 4,
    questions: [
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
    ],
  },
  {
    id: 37,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
    ],
  },
  {
    id: 38,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
    ],
  },
  {
    id: 39,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
    ],
  },
  {
    id: 40,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
    ],
  },
  {
    id: 41,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
      require('@/assets/images/questions/weather/weather-19.svg'),
      require('@/assets/images/questions/weather/weather-20.svg'),
    ],
  },
  {
    id: 42,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
    ],
  },
  {
    id: 43,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-6.svg'),
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
    ],
  },
  {
    id: 44,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
    ],
  },
  {
    id: 45,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-16.svg'),
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
      require('@/assets/images/questions/weather/weather-19.svg'),
      require('@/assets/images/questions/weather/weather-20.svg'),
    ],
  },
  {
    id: 46,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-1.svg'),
      require('@/assets/images/questions/weather/weather-2.svg'),
      require('@/assets/images/questions/weather/weather-3.svg'),
      require('@/assets/images/questions/weather/weather-4.svg'),
      require('@/assets/images/questions/weather/weather-5.svg'),
      require('@/assets/images/questions/weather/weather-6.svg'),
    ],
  },
  {
    id: 47,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-7.svg'),
      require('@/assets/images/questions/weather/weather-8.svg'),
      require('@/assets/images/questions/weather/weather-9.svg'),
      require('@/assets/images/questions/weather/weather-10.svg'),
      require('@/assets/images/questions/weather/weather-11.svg'),
      require('@/assets/images/questions/weather/weather-12.svg'),
    ],
  },
  {
    id: 48,
    theme: LevelTheme.Weather,
    type: LevelType.ImageUrl,
    matchCount: 5,
    questions: [
      require('@/assets/images/questions/weather/weather-13.svg'),
      require('@/assets/images/questions/weather/weather-14.svg'),
      require('@/assets/images/questions/weather/weather-15.svg'),
      require('@/assets/images/questions/weather/weather-16.svg'),
      require('@/assets/images/questions/weather/weather-17.svg'),
      require('@/assets/images/questions/weather/weather-18.svg'),
    ],
  },
];
